version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: es7
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend

networks:
  backend:
    driver: bridge
