openapi: 3.0.0
info:
  title: 산업용어 통합검색 API
  version: 1.0.0
  description: 금속/통상/산업약어 분야의 용어 검색 및 즐겨찾기 기능 제공

servers:
  - url: /api/v1

paths:
  /search:
    get:
      summary: 산업용어 통합 검색
      description: 엘라스틱서치를 이용한 통합 검색. 용어 해설, 출처, 분야 정보가 포함됩니다.
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          required: true
          description: 검색할 용어나 약어
        - in: query
          name: category
          schema:
            type: string
            enum: [금속, 통상, 산업]
          required: false
          description: 분야 필터
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 검색 결과 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'

  /favorites:
    get:
      summary: 즐겨찾기 목록 조회
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 즐겨찾기 리스트 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FavoriteItem'

    post:
      summary: 즐겨찾기 추가
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavoriteRequest'
      responses:
        '201':
          description: 즐겨찾기 추가 성공

    delete:
      summary: 즐겨찾기 제거
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: termId
          schema:
            type: string
          required: true
          description: 즐겨찾기 삭제 대상 용어 ID
      responses:
        '204':
          description: 즐겨찾기 삭제 성공

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SearchResults:
      type: object
      properties:
        total:
          type: integer
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchItem'

    SearchItem:
      type: object
      properties:
        id:
          type: string
        term:
          type: string
        explanation:
          type: string
        source:
          type: string
        category:
          type: string
          enum:
            - 금속
            - 통상
            - 약어

    FavoriteItem:
      type: object
      properties:
        id:
          type: string
        term:
          type: string
        category:
          type: string
          enum:
            - 금속
            - 통상
            - 산업
        addedAt:
          type: string
          format: date-time

    FavoriteRequest:
      type: object
      properties:
        termId:
          type: string
          description: 즐겨찾기 대상 용어 ID
      required:
        - termId
